language: go

go:
  - 1.7.x

before_install:
  - go get golang.org/x/net/context
  - go get github.com/Sirupsen/logrus
  - go get google.golang.org/grpc
  - go get github.com/stretchr/testify/mock
  - go get github.com/davecgh/go-spew/spew
  - go get github.com/pmezard/go-difflib/difflib
  - go get github.com/stretchr/objx
  - go get github.com/stretchr/testify/assert
  - go get github.com/stretchr/testify/require
  - go get github.com/satori/go.uuid

script:
  - go test -v ./...

notifications:
  slack:
    secure: KUc8ZrE3lCM+ZiUrosvq0kfX9HwYUVQBEe7N4rlv7MsgfDhrHjLsRZVJIBzAJ72XAnQwVqkPVSh/7UVhyO1BDCz/Bf0yirZHTaUlcnFT1Gp/aPoOeAQiikNnOTCuwf2ssTf9FePe+/aHm5FK8ZiAg4ZPz4EeIf9tKZf37VLOlsn8VCb+sqCY6knv+K8lbWtmtzgbJdzS2+rOYDGyRzW+4Hl05EXsXd5BXEhS/mCXpc640wbde1Q0dFgFfBnSAJrJAaOjuiXPZnZFOpYQP9dFc+Xf36hpCZGW89NMDyq++ZgYT2+6Gf6okQXhfaGWiEHIlnpUdXtogQKNPn94GADveCV1Zdtgpw2xppBFsz3CfY2CTv81ghHgZ/UNZsBL843Ue2E/o3T1xKhTaGz3myvbxVhcXy/p16vTGaPMqUfxcbEwh2ilA0Cy+t7/YjaCLfqlA+m6uybdYPnxLZUV93Xpbu4odDDQQVKMAWJwoVILMUnXGZMjcqJ3RXvFIErzyWTJcyPdjhOTSLgLigC4r3jSgySy6ey/uBOmrKSH3ew5Iu6Bk5Ut4jruGgtgx4LNkOelZtj40FxEscbbLAaZHX7yHt9i179jSp3pvKO7lKbz+PZCVXGVDE5dm30lM/3VEEScEszVQlLe8k7lKEKlgaQhBdxsA6cI4F6tjYNkpYai7VI=
